---
- name: Create magma configs directory
  file:
    path: /var/opt/magma/configs
    state: directory

- name: Copy control_proxy.yml for Magma Orchestrator
  template:
    src: control_proxy.yml.j2
    dest: /var/opt/magma/configs/control_proxy.yml

- name: Create magma certs directory
  file:
    path: /var/opt/magma/tmp/certs
    state: directory

- name: Download rootCA.pem for {{ orc8r_domain }}
  get_url:
    url: "{{ rootca_pem_url }}"
    dest: /var/opt/magma/tmp/certs/rootCA.pem
